
<Style name="contours10">
        <Rule>
                <MaxScaleDenominator>70000</MaxScaleDenominator>
                <MinScaleDenominator>500</MinScaleDenominator>
                <LineSymbolizer>
                        <CssParameter name="stroke">#ADC4B0</CssParameter>
                        <CssParameter name="stroke-width">.5</CssParameter>
						<CssParameter name="stroke-dasharray">2,2</CssParameter>
                </LineSymbolizer>
        </Rule>
</Style>
<Style name="contours50">
        <Rule>
                <MaxScaleDenominator>204741</MaxScaleDenominator>
                <MinScaleDenominator>500</MinScaleDenominator>
                <LineSymbolizer>
                        <CssParameter name="stroke">#ADC4B0</CssParameter>
                        <CssParameter name="stroke-width">.5</CssParameter>
						<CssParameter name="stroke-dasharray">2,2</CssParameter>
                </LineSymbolizer>
        </Rule>
</Style>
<Style name="contours100">
        <Rule>
                <MaxScaleDenominator>409483</MaxScaleDenominator>
                <MinScaleDenominator>204741</MinScaleDenominator>
                <LineSymbolizer>
                        <CssParameter name="stroke">#ADC4B0</CssParameter>
                        <CssParameter name="stroke-width">.5</CssParameter>
						<CssParameter name="stroke-dasharray">2,2</CssParameter>
                </LineSymbolizer>
        </Rule>
        <Rule>
                <MaxScaleDenominator>204741</MaxScaleDenominator>
                <MinScaleDenominator>51185</MinScaleDenominator>
                <LineSymbolizer>
                        <CssParameter name="stroke">#ADC4B0</CssParameter>
                        <CssParameter name="stroke-width">.5</CssParameter>
						<CssParameter name="stroke-dasharray">2,2</CssParameter>
                </LineSymbolizer>
        </Rule>
        <Rule>
                <MaxScaleDenominator>51185</MaxScaleDenominator>
                <MinScaleDenominator>1599</MinScaleDenominator>
                <LineSymbolizer>
                        <CssParameter name="stroke">#ADC4B0</CssParameter>
                        <CssParameter name="stroke-width">.5</CssParameter>
                </LineSymbolizer>
        </Rule>
</Style>
<Style name="contours-text50">
        <Rule>
                <MaxScaleDenominator>51185</MaxScaleDenominator>
                <MinScaleDenominator>1599</MinScaleDenominator>
                <TextSymbolizer name="height" face_name="DejaVu Sans Book" size="8" fill="#ADC4B0" halo_radius="1"/>
        </Rule>
</Style>
<Style name="contours-text100">
        <Rule>
                <MaxScaleDenominator>102370</MaxScaleDenominator>
                <MinScaleDenominator>51185</MinScaleDenominator>
                <TextSymbolizer name="height" face_name="DejaVu Sans Book" size="8" fill="#ADC4B0" halo_radius="1" />
        </Rule>
        <Rule>
                <MaxScaleDenominator>51185</MaxScaleDenominator>
                <MinScaleDenominator>1599</MinScaleDenominator>
                <TextSymbolizer name="height" face_name="DejaVu Sans Book" size="8" fill="#ADC4B0" halo_radius="1" />
        </Rule>
</Style>
